name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitpipe
      
    - name: Tagging the Docker Image
      run: docker tag my-image-name asia.gcr.io/windy-nova-380710/gitpipe
      
    - name: Pushing the Docker Image
      run: docker push asia.gcr.io/windy-nova-380710/gitpipe
